Service conversions
Sparkz-Community/roles-client-lib pull request #1
Opened 2022-08-16 18:01 UTC by Raymondo97

2022-08-16 18:29 UTC, Raymondo97 commented
Changes discussed have been made.

2022-08-17 18:32 UTC, dallinbjohnson requested changes

2022-08-17 18:32 UTC, dallinbjohnson commented on src/stores/services/abilities.js
> +    state = {},
this needs to be a function `state = () => ({})`

2022-08-17 19:42 UTC, Raymondo97 commented on src/stores/services/abilities.js
> +    state = {},
The change has been made for all services.

2022-08-17 21:17 UTC, dallinbjohnson approved these changes

2022-08-17 21:17 UTC, merged